name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Run Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.override.yml up -d --build
          sleep 10  # Beri waktu kontainer untuk naik
          docker ps
          
      - name: Check Flask API
        run: |
          curl -f http://localhost:5000 || exit 1
