name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and tag Flask app
      run: docker build -t flask-app ./app

    - name: Build and tag Backend app
      run: docker build -t backend-app ./backend

    - name: Run docker-compose
      run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build
